### ISSUE TITLE
Graphical boot Splash screen hides boot errors

### ISSUE THREAD

**Issue by rmx-it** [trueos/trueos-core#134]
Hi,
I'm currently having not only a boot error (where a second error message will be opened) but
a error due to the new boot splash screen, which hides the other error and makes is impossible
to analyze or fix the other error:

- I can't seem to be able to temporary disable the splash screen during startup
- The splash screen hangs forever in case of a mount error
- I do not see the mount error 
- To disable the splash screen I need a mounted root...

So please disable the graphical boot splash screen per default as it hides errors or 
add a knob (ESC?) to disable it temporary...

Thanks!

Greetings
---
mike

**Comment by pkgdemon** [comment]
You can press 3 to escape to loader prompt.  Then type:

```set boot_mute="NO"```
```boot```

That will remove the boot splash when booting.

**Comment by lukebakken** [comment]
@pkgdemon - I tried that at both the loader prompt, and by editing `/boot/loader.conf.trueos`. Neither method disabled the splash screen for me. I would like it permanently disabled.

I am running TrueOS in VirtualBox, installed from the 2016-12-15 DVD iso and updated to the latest version via the built-in updater.

**Comment by pkgdemon** [comment]
We have fixed this so if you choose verbose boot at the loader it will hide the splash.

**Comment by lukebakken** [comment]
Great, thanks. I'll give it a try. I'm assuming this setting can be saved in `/boot/loader.conf.trueos` as well?

**Comment by pkgdemon** [comment]
You can try boot_verbose="YES" in that file.

**Comment by lukebakken** [comment]
Hmm, well, I tried `boot_verbose="YES"` and "verbose="YES"` in the loader prompt an in the file, and still see the TrueOS splash screen. Obviously, this is not the end of the world.
